import type { StepStatus, StepStatusConfig, ComplianceRule, CompliancePhase, DocumentType } from './types';

// Status configuration for UI rendering — pastel bg + dark text (no neon)
export const STATUS_CONFIG: Record<StepStatus, StepStatusConfig> = {
  not_started: {
    color: 'text-gray-600',
    bgColor: 'bg-gray-100',
    borderColor: 'border-gray-200',
    iconName: 'Circle',
    label: 'Not Started',
    description: 'This step has not been started yet',
  },
  waiting: {
    color: 'text-amber-700',
    bgColor: 'bg-neutral-100',
    borderColor: 'border-amber-200',
    iconName: 'Clock',
    label: 'Waiting on Caregiver',
    description: 'Documents requested, awaiting submission',
  },
  uploaded: {
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    borderColor: 'border-blue-200',
    iconName: 'Upload',
    label: 'Need Review',
    description: 'Documents uploaded, pending verification',
  },
  verified: {
    color: 'text-green-700',
    bgColor: 'bg-neutral-100',
    borderColor: 'border-green-200',
    iconName: 'CheckCircle2',
    label: 'Verified',
    description: 'Admin has verified and approved',
  },
  blocked: {
    color: 'text-red-700',
    bgColor: 'bg-neutral-200',
    borderColor: 'border-red-200',
    iconName: 'AlertCircle',
    label: 'Blocked',
    description: 'Fails compliance requirements',
  },
};

// Hard compliance gate rules - these block assignment when not verified
export const COMPLIANCE_GATES: ComplianceRule[] = [
  {
    id: 'cori_cleared',
    name: 'CORI Background Check',
    description: 'Criminal Offender Record Information must be cleared',
    stepIds: ['step-5'],
    blocksAssignment: true,
    errorMessage: 'CORI background check not cleared',
    checkType: 'all_verified',
  },
  {
    id: 'sori_cleared',
    name: 'SORI Background Check',
    description: 'Sex Offender Registry Information must be cleared',
    stepIds: ['step-5'],
    blocksAssignment: true,
    errorMessage: 'SORI background check not cleared',
    checkType: 'all_verified',
  },
  {
    id: 'training_passed',
    name: 'Training Assessment',
    description: 'Training assessment score must be >= 80%',
    stepIds: ['step-6'],
    blocksAssignment: true,
    errorMessage: 'Training score below 80%',
    checkType: 'all_verified',
  },
  {
    id: 'onboarding_packet',
    name: 'Onboarding Packet',
    description: 'All policy acknowledgements must be signed',
    stepIds: ['step-7'],
    blocksAssignment: true,
    errorMessage: 'Onboarding packet incomplete',
    checkType: 'all_verified',
  },
  {
    id: 'i9_complete',
    name: 'I-9 Employment Verification',
    description: 'Federal I-9 form must be completed within 3 business days',
    stepIds: ['step-9', 'step-10', 'step-11'],
    blocksAssignment: true,
    errorMessage: 'I-9 employment verification incomplete',
    checkType: 'all_verified',
  },
  {
    id: 'emergency_contact',
    name: 'Emergency Contact',
    description: 'Emergency contact information must be on file',
    stepIds: ['step-7'],
    blocksAssignment: true,
    errorMessage: 'No emergency contact on file',
    checkType: 'all_verified',
  },
  {
    id: 'payroll_setup',
    name: 'Payroll Setup',
    description: 'Payroll forms must be completed',
    stepIds: ['step-12'],
    blocksAssignment: true,
    errorMessage: 'Payroll setup incomplete',
    checkType: 'all_verified',
  },
];

// Document type labels for UI
export const DOCUMENT_TYPE_LABELS: Record<DocumentType, string> = {
  application: 'Application',
  cori: 'CORI Authorization',
  sori: 'SORI Search Record',
  training: 'Training Certificate',
  i9: 'I-9 Document',
  policy: 'Policy Acknowledgement',
  emergency: 'Emergency Contact',
  w4: 'W-4 Form',
  direct_deposit: 'Direct Deposit Form',
  offer_letter: 'Offer Letter',
  reference: 'Reference Check',
  interview: 'Interview Evaluation',
  transportation: 'Transportation Docs',
  other: 'Other Document',
};

// Default caregiver phases data structure
export const DEFAULT_CAREGIVER_PHASES: CompliancePhase[] = [
  {
    id: 'phase-1',
    phaseNumber: 1,
    phaseName: 'Pre-Offer Screening',
    goal: 'Decide if the caregiver is eligible to hire',
    status: 'in_progress',
    phaseStatus: 'Internal review',
    steps: [
      {
        id: 'step-1',
        stepNumber: 1,
        title: 'Application + Caregiver Intake',
        description: 'Caregiver Application Form & Caregiver Intake Form',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['application'],
        isComplianceGate: false,
        outcome: 'Application on file',
        auditHistory: [],
      },
      {
        id: 'step-2',
        stepNumber: 2,
        title: 'Initial Interview',
        description: 'Phone / Video / In-person | Interview Evaluation Form required',
        status: 'not_started',
        method: 'Video',
        documents: [],
        requiredDocumentTypes: ['interview'],
        isComplianceGate: false,
        outcome: 'Interview approved or rejected',
        noDocumentUpload: true,
        auditHistory: [],
      },
      {
        id: 'step-3',
        stepNumber: 3,
        title: 'Reference Checks',
        description: 'Minimum 2 references (professional preferred) | Document: Date, Contact, Summary',
        status: 'not_started',
        requiredCount: 2,
        completedCount: 0,
        documents: [],
        requiredDocumentTypes: ['reference'],
        isComplianceGate: false,
        outcome: 'Phase 1 complete → unlock offer',
        noDocumentUpload: true,
        auditHistory: [],
      },
    ],
  },
  {
    id: 'phase-2',
    phaseNumber: 2,
    phaseName: 'Conditional Offer',
    goal: 'Establish intent before compliance checks',
    status: 'locked',
    phaseStatus: 'Offer pending',
    lockedUntil: 'phase-1',
    steps: [
      {
        id: 'step-4',
        stepNumber: 4,
        title: 'Issue Conditional Offer Letter',
        description: 'Includes acknowledgment of: CORI/SORI clearance, Required training completion, I-9 completion by Day 1, Availability & policy acknowledgements, At-will employment',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['offer_letter'],
        isComplianceGate: false,
        outcome: 'Offer accepted → unlock compliance',
        auditHistory: [],
      },
    ],
  },
  {
    id: 'phase-3',
    phaseNumber: 3,
    phaseName: 'Post-Offer Compliance Setup',
    goal: 'Massachusetts + agency compliance',
    status: 'locked',
    phaseStatus: 'Compliance in progress',
    lockedUntil: 'phase-2',
    steps: [
      {
        id: 'step-5',
        stepNumber: 5,
        title: 'Background Checks',
        description: 'CORI Authorization + Results (confidential) | SORI Search Record (best practice)',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['cori', 'sori'],
        isComplianceGate: true,
        complianceRuleId: 'cori_cleared',
        outcome: 'Cannot proceed without CORI clearance',
        auditHistory: [],
      },
      {
        id: 'step-6',
        stepNumber: 6,
        title: 'Training & Certification',
        description: 'Training module assigned | Assessment completed | Passing score ≥ 80% | Certification auto-generated',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['training'],
        isComplianceGate: true,
        complianceRuleId: 'training_passed',
        outcome: 'Training passed',
        auditHistory: [],
      },
      {
        id: 'step-7',
        stepNumber: 7,
        title: 'Onboarding Packet',
        description: 'Signed acknowledgements: HIPAA/Confidentiality, Code of Conduct, Abuse & Neglect Reporting, Handbook, Availability Confirmation, Emergency Contact, Fitness-for-Duty (self-attestation)',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['policy', 'emergency'],
        isComplianceGate: true,
        complianceRuleId: 'onboarding_packet',
        outcome: 'All acknowledgements signed',
        auditHistory: [],
      },
      {
        id: 'step-8',
        stepNumber: 8,
        title: 'Transportation Readiness',
        description: 'Conditional logic: If driving → Driver\'s License, Auto Insurance | If not driving → Transportation Acknowledgement',
        status: 'not_started',
        conditional: {
          field: 'driving',
          value: true,
        },
        documents: [],
        requiredDocumentTypes: ['transportation'],
        isComplianceGate: false,
        outcome: 'Transportation verified',
        auditHistory: [],
      },
    ],
  },
  {
    id: 'phase-4',
    phaseNumber: 4,
    phaseName: 'Day 1 Employment Verification',
    goal: 'Federal employment compliance',
    status: 'locked',
    phaseStatus: 'Time-bound',
    lockedUntil: 'phase-3',
    steps: [
      {
        id: 'step-9',
        stepNumber: 9,
        title: 'I-9 Section 1 (Caregiver)',
        description: 'Completed no later than Day 1',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['i9'],
        isComplianceGate: true,
        complianceRuleId: 'i9_complete',
        outcome: 'Section 1 complete',
        auditHistory: [],
      },
      {
        id: 'step-10',
        stepNumber: 10,
        title: 'I-9 Document Review (Employer)',
        description: 'Verify original, unexpired documents | Use I-9 checklist',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['i9'],
        isComplianceGate: true,
        complianceRuleId: 'i9_complete',
        outcome: 'Documents verified',
        noDocumentUpload: true,
        auditHistory: [],
      },
      {
        id: 'step-11',
        stepNumber: 11,
        title: 'I-9 Section 2 (Employer)',
        description: 'Completed within 3 business days | Stored separately from personnel file',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['i9'],
        isComplianceGate: true,
        complianceRuleId: 'i9_complete',
        outcome: 'I-9 (Section 1 + 2) complete',
        noDocumentUpload: true,
        auditHistory: [],
      },
    ],
  },
  {
    id: 'phase-5',
    phaseNumber: 5,
    phaseName: 'Payroll Setup',
    goal: 'Ensure caregiver can be paid legally',
    status: 'locked',
    phaseStatus: 'Admin setup',
    lockedUntil: 'phase-4',
    steps: [
      {
        id: 'step-12',
        stepNumber: 12,
        title: 'Payroll Forms',
        description: 'W-4 | Direct Deposit / Pay Card Consent | MA New Hire Reporting (internal)',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: ['w4', 'direct_deposit'],
        isComplianceGate: true,
        complianceRuleId: 'payroll_setup',
        outcome: 'Payroll setup complete',
        auditHistory: [],
      },
    ],
  },
  {
    id: 'phase-6',
    phaseNumber: 6,
    phaseName: 'Ready to Assign',
    goal: 'Final safety & compliance gate',
    status: 'locked',
    phaseStatus: 'System-validated',
    lockedUntil: 'phase-5',
    steps: [
      {
        id: 'step-13',
        stepNumber: 13,
        title: 'System Validation (AUTO)',
        description: 'Caregiver is marked READY TO ASSIGN only if ALL are complete: Conditional offer accepted, CORI cleared, SORI cleared, Training passed, All policy acknowledgements signed, I-9 (Section 1 + 2) complete, Payroll setup complete, Emergency contact on file',
        status: 'not_started',
        autoValidation: true,
        documents: [],
        requiredDocumentTypes: [],
        isComplianceGate: false,
        outcome: 'No manual checkbox (optional admin override with audit log)',
        auditHistory: [],
      },
      {
        id: 'step-14',
        stepNumber: 14,
        title: 'First Assignment + Care Plan Review',
        description: 'Match caregiver to client | Review: Care plan, Safety risks, Dementia needs, Pets/home hazards | Confirm schedule & reporting | Deliver: First-Day One-Pager, Name Badge (mandatory)',
        status: 'not_started',
        documents: [],
        requiredDocumentTypes: [],
        isComplianceGate: false,
        outcome: 'First assignment completed',
        noDocumentUpload: true,
        auditHistory: [],
      },
    ],
  },
];

// Phase colors for timeline
export const PHASE_COLORS = {
  complete: {
    bg: 'bg-black',
    border: 'border-green-500',
    text: 'text-green-600',
    ring: 'ring-green-500',
  },
  in_progress: {
    bg: 'bg-neutral-700',
    border: 'border-blue-500',
    text: 'text-blue-600',
    ring: 'ring-blue-500',
  },
  locked: {
    bg: 'bg-gray-300',
    border: 'border-gray-300',
    text: 'text-gray-500',
    ring: 'ring-gray-300',
  },
  blocked: {
    bg: 'bg-black',
    border: 'border-red-500',
    text: 'text-red-600',
    ring: 'ring-red-500',
  },
};
